site_name: "translate-the-docs"
site_url: https://pages.charlesreid1.com/translate-the-docs
repo_name: translate-the-docs
repo_url: https://git.charlesreid1.com/charlesreid1/translate-the-docs

copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>, released under the <a href="https://opensource.org/licenses/MIT">MIT License</a>.<br />Photo Credit: <a href="https://www.flickr.com/photos/russloar/">Russ Loar</a> under the <a href="https://creativecommons.org/licenses/by-nc-nd/2.0/">CC BY-NC-ND License</a>'

docs_dir: ruskie_docs
site_dir: site
extra_css:
  - css/custom.css
theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo:
    icon: 'settings_input_component'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
pages:
  - 'Home':               'index.md'
  - 'Organization':       'Organization.md'
  - 'Setup':              'Setup.md'
  - 'Pandoc: Part 1' :    'PandocA.md'
  - 'Pandoc: Part 2' :    'PandocB.md'
  - 'Panflute: Part 1' :  'PanfluteA.md'
  - 'Panflute: Part 2' :  'PanfluteB.md'
  - 'Pandoc: Part 3' :    'PandocC.md'
  - 'Testing':            'Testing.md'
  - 'Links':              'Links.md'

