site_name: "translate-yer-docs"
site_url: https://pages.charlesreid1.com/translate-yer-docs
repo_name: translate-yer-docs
repo_url: https://git.charlesreid1.com/charlesreid1/translate-yer-docs

copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>, released under the <a href="https://opensource.org/licenses/MIT">MIT License</a>.'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo:
    icon: 'insert_drive_file arrow_right_alt g_translate arrow_right_alt insert_drive_file'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
pages:
  - 'Home':               'index.md'
  - 'Organization':       'Organization.md'
  - 'Setup':              'Setup.md'
  - 'Pandoc: Part 1' :    'PandocA.md'
  - 'Pandoc: Part 2' :    'PandocB.md'
  - 'Panflute: Part 1' :  'PanfluteA.md'
  - 'Panflute: Part 2' :  'PanfluteB.md'
  - 'Pandoc: Part 3' :    'PandocC.md'
  - 'Testing':            'Testing.md'
  - 'Links':              'Links.md'

